class IncorrectFields(BaseException): ...

class ObjectNotCreated(BaseException): ...

class ObjectDoesntExist(BaseException): ...

class NoMandatoryFields(BaseException): ...

class NoEmailOrPasswordFields(BaseException): ...

class EmailOrPasswordIncorrect(BaseException): ...

class TokenError(BaseException): ...

class ExpiredToken(BaseException): ...

class InvalidToken(BaseException): ...

class NoUniqueEmail(BaseException): ...

class WrongPassword(BaseException): ...

class WrongEmail(BaseException): ...

class WrongNames(BaseException): ...

class WrongDates(BaseException): ...

class ReservationNotPossible(BaseException): ...